name: Ed-Eater PR Lint Check

on:
  pull_request:
    branches: [main]

jobs:
  pr_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build and check lint
        run: npm run build
